default_install_hook_types: [pre-commit, commit-msg]
default_language_version:
  python: python3
default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]

      - id: black
        name: black
        entry: black
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

      - id: commitizen
        name: check commit msg
        entry: cz check --commit-msg-file
        language: python
        stages: [commit-msg]

      - id: mypy
        name: mypy
        entry: mypy .
        language: python
        types: [python]
        pass_filenames: false

      # - id: pytest
      #   name: pytest
      #   entry: pytest tests
      #   language: python
      #   types: [python]
      #   pass_filenames: false
